//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoezWork_Buivanchat_18607075.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int BranchId { get; set; }
        public string NameBranch { get; set; }
        public string MaDviqly { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> BranchParent { get; set; }
        public string Address { get; set; }
        public Nullable<int> WardId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Type { get; set; }
        public string ProvinceName { get; set; }
        public string DistrictName { get; set; }
        public string WardName { get; set; }
        public Nullable<decimal> MaxDebitAmount { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<System.DateTime> CooperationDay { get; set; }
        public Nullable<int> TotalDepartment { get; set; }
        public Nullable<int> TotalStaff { get; set; }
        public Nullable<bool> Notdisplaysizecolor { get; set; }
        public string MA_DVIQLY { get; set; }
        public Nullable<bool> IsDisplay { get; set; }
    }
}
