//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoezWork_Buivanchat_18607075.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Graduation_Project_Work_ManagementEntities : DbContext
    {
        public Graduation_Project_Work_ManagementEntities()
            : base("name=Graduation_Project_Work_ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountUser> AccountUsers { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<PositionUser> PositionUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<WProject> WProjects { get; set; }
        public virtual DbSet<WProjectGroup> WProjectGroups { get; set; }
        public virtual DbSet<WProjectItem> WProjectItems { get; set; }
        public virtual DbSet<WProjectPerson> WProjectPersons { get; set; }
        public virtual DbSet<WTypeOfWork> WTypeOfWorks { get; set; }
        public virtual DbSet<WWork> WWorks { get; set; }
        public virtual DbSet<WWorkAtt> WWorkAtts { get; set; }
        public virtual DbSet<WWorkBrowse> WWorkBrowses { get; set; }
        public virtual DbSet<WWorkChat> WWorkChats { get; set; }
        public virtual DbSet<WWorkCustomer> WWorkCustomers { get; set; }
        public virtual DbSet<WWorkDetail> WWorkDetails { get; set; }
        public virtual DbSet<WWorkDetailPerson> WWorkDetailPersons { get; set; }
        public virtual DbSet<WWorkLog> WWorkLogs { get; set; }
        public virtual DbSet<WWorkPerson> WWorkPersons { get; set; }
        public virtual DbSet<WWorkRate> WWorkRates { get; set; }
        public virtual DbSet<WWorkReport> WWorkReports { get; set; }
    }
}
