//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoezWork_Buivanchat_18607075.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public bool Sex { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public Nullable<int> LoginFailedCount { get; set; }
        public Nullable<int> LoginFailedCount2 { get; set; }
        public Nullable<int> LoginFailedCount3 { get; set; }
        public Nullable<System.DateTime> LastChangedPassword { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string ProfileImage { get; set; }
        public Nullable<int> PositionId { get; set; }
    }
}
