//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoezWork_Buivanchat_18607075.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public int UserTypeId { get; set; }
        public string UserCode { get; set; }
        public string UserTypeName { get; set; }
    }
}
