//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoezWork_Buivanchat_18607075.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WProjectPerson
    {
        public int ProjectPersionId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<int> AssignedUserId { get; set; }
        public string MaDviqly { get; set; }
    }
}
