//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoezWork_Buivanchat_18607075.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WProjectItem
    {
        public int ProjectItemId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string CodeItem { get; set; }
        public string NameItem { get; set; }
        public Nullable<System.DateTime> StartDay { get; set; }
        public Nullable<System.DateTime> EndDay { get; set; }
        public Nullable<decimal> PercentEstimate { get; set; }
        public Nullable<decimal> PercentEstimateTotal { get; set; }
        public Nullable<decimal> PercentExcute { get; set; }
        public Nullable<decimal> PercentExcuteTotal { get; set; }
        public string Code { get; set; }
        public string Discription { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<int> AssignedUserId { get; set; }
        public string MaDviqly { get; set; }
    }
}
