//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoezWork_Buivanchat_18607075.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WWork
    {
        public int Workid { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Point { get; set; }
        public Nullable<decimal> PointTotal { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsOnepersion { get; set; }
        public Nullable<int> ExcuSequenceDocumentid { get; set; }
        public Nullable<int> SequencedocumentStepid { get; set; }
        public Nullable<System.DateTime> TimeremindFinish { get; set; }
        public Nullable<byte> IsRating { get; set; }
        public Nullable<int> TypeRating { get; set; }
        public Nullable<int> TypeWork { get; set; }
        public Nullable<int> WorkLevel { get; set; }
        public Nullable<int> Documentaryid { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsTemplate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<int> AssignedUserId { get; set; }
        public string MaDviqly { get; set; }
    }
}
