//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoezWork_Buivanchat_18607075.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WWorkRate
    {
        public int WorkRateid { get; set; }
        public Nullable<int> Workid { get; set; }
        public Nullable<bool> Volume { get; set; }
        public Nullable<bool> Quality { get; set; }
        public Nullable<bool> Progress { get; set; }
        public Nullable<double> Point { get; set; }
        public Nullable<bool> Result { get; set; }
        public Nullable<System.DateTime> EndtDate { get; set; }
        public Nullable<int> RateUserId { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<int> AssignedUserId { get; set; }
        public string MaDviqly { get; set; }
    }
}
