//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoezWork_Buivanchat_18607075.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WWorkAtt
    {
        public int WorkAttid { get; set; }
        public Nullable<int> Workid { get; set; }
        public string Passunlockfile { get; set; }
        public string Pathfile { get; set; }
        public string TypeFile { get; set; }
        public Nullable<decimal> SizeofFile { get; set; }
        public Nullable<decimal> SizeofFileTotal { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<int> AssignedUserId { get; set; }
        public string MaDviqly { get; set; }
    }
}
